---
apiVersion: extensions/v1beta1
kind: Cluster
metadata:
  name: es-client
  labels:
    app: es-client
    component: elasticsearch
    role: services
spec:
  replicas: 1
  template:
    spec:
      serviceaccountName: cluster-account
      providers:
      - name: gke
        project: trials
        version: 1.9.7
        image: cos
        region: europe-west2
        # zone: europe-west2-a
        network: default
        dashboard: true
        monitoring: true
        autoscaling: true
        bootdisk: 100GB
        localssd: 
        nodePools:
        - name: toto
          nodePerZone: 1
          nodeType: n1-standard-2
          image: ubuntu
        - name: toto
          nodePerZone: 1
          nodeType: n1-standard-2
          image: ubuntu

      - name: aws
        version: 1.9.7
        image: cos
        region:
          - europe-west2
        network: default
        dashboard: true
        monitoring: true
        autoscaling: true
        bootdisk: 100GB
        localssd: 
        nodePools:
          - name: toto
            nodePerZone: 1
            nodeType: n1-standard-2
            image: ubuntu
      - name: toto
        nodePerZone: 1
        nodeType: n1-standard-2
        image: ubuntu 
